services:
  backend:
    build: ./Api/WordCardsApi
    ports:
      - "5071:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - MongoDb__ConnectionURI=mongodb://mongodb:27017
      - MongoDb__DatabaseName=WordCardsApi
    depends_on:
      - mongodb

  frontend:
    build: ./React/my-app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongodb:
    image: mongo:8.0.28
    ports:
      - "27017:27017"